controller_frequency: 5.0
recovery_behaviour_enabled: true

TebLocalPlannerROS:
  
  # Robot Configuration Parameters
  max_vel_x: 10.0
  max_vel_x_backwards: 1.0
  max_vel_theta: 3.2
  acc_lim_x: 13.26
  weight_kinematics_forward_drive: 1000
  wheelbase: 0.3302
  acc_lim_theta: 20.0

  holonomic_robot: false
  sim_time: 3

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  meter_scoring: true
  free_goal_vel: true
  
  # Trajectory Parameters
  
  dt_ref: 0.7
  dt_hysteresis: 0.07
#min_samples: 9.0
  feasibility_check_no_poses: 0.0
  feasibility_check_lookahead_distance: 0.0
#max_global_plan_lookahead_dist: 0.0
  min_obstacle_dist: 0.5
#weight_max_vel_x: 100.0
#weight_acc_lim_*: 10.0


  
  # Obstacles Paramaters
  
#inflation_dist: 1.0
#min_obstacle_dist
