footprint: [[-0.1, -0.2], [-0.1, 0.2], [0.4, 0.2], [0.4, -0.2]]
footprint_padding: 0.1

robot_base_frame: ego_racecar/base_link
#transform_tolerance: 0.5
resolution: 0.25

obstacle_range: 5.5
raytrace_range: 7.0
#6.0

#layer definitions
static:
  map_topic: map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser_sensor
  laser_sensor: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
  inflation_radius: .8
