local_costmap:
  global_frame: map
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  update_frequency: 100.0
  publish_frequency: 100.0
  transform_tolerance: 0.1
# footprint_padding: 0.1


  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
